[versions]
jvm = "25"
kotlin = "2.4.10"
tenter = "0.1.0-SNAPSHOT"
junit = "6.1.0"
mockk = "1.14.11"
assertj = "3.27.7"
konsist = "0.17.3"
mordant = "3.0.2"
kotlinx-coroutines = "1.11.0"
spotless = "8.10.3"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[bundles]
junit = ["junit-jupiter-api", "junit-jupiter-engine", "junit-jupiter-params"]
